kind: pipeline
name: default

steps:
- name: kaniko
  image: banzaicloud/drone-kaniko
  settings:
    username: 
      from_secret: docker-hub-username
    password: 
      from_secret: docker-hub-password
    repo: registry.kramergroup.science/workflows/matsci-base
    build_args: 
    - S3_ACCESS_KEY_ID
    - S3_SECRET_ACCESS_KEY
    - S3_HOST
    secrets: [S3_ACCESS_KEY_ID,S3_SECRET_ACCESS_KEY,S3_HOST]
