kind: pipeline
name: default

steps:
- name: get-psps
  image: viant/s3cmd:latest
  volumes:
  - name: psps
    path: /tmp/psps
  environment:
    S3_PSPS_URL:
      from_secret: s3-psps-url
    S3_ACCESS_KEY_ID:
      from_secret: aws-access-key-id
    S3_SECRET_ACCESS_KEY:
      from_secret: aws-secret-access-key
    S3_HOST:
      from_secret: s3-host
  commands:
  - s3cmd --access_key=${S3_ACCESS_KEY_ID} --secret_key=${S3_SECRET_ACCESS_KEY} --host=${S3_HOST} get s3://vasp/vasp5_psps.tar.gz /tmp/psps/vasp5_psps.tar.gz


volumes:
- name: psps
  temp: {}