kind: pipeline
name: default

steps:
- name: get-psps
  image: minio/mc
  volumes:
  - name: psps
    path: /tmp/psps
  environment:
    S3_ACCESS_KEY_ID:
      from_secret: aws-access-key-id
    S3_SECRET_ACCESS_KEY:
      from_secret: aws-secret-access-key
    S3_HOST:
      from_secret: s3-host
  commands:
  - mc config host add minio https://$S3_HOST $S3_ACCESS_KEY_ID $S3_SECRET_ACCESS_KEY
  - mc ls minio/vasp

volumes:
- name: psps
  temp: {}